# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        path: .
        dockerfile: ./Dockerfile
    
    - name: Install AWS CLI 
      run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Build, tag, and push image
      run: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 042072295322.dkr.ecr.us-east-1.amazonaws.com
            docker build -t awstask .
            docker tag awstask:latest 042072295322.dkr.ecr.us-east-1.amazonaws.com/awstask:latest
            docker push 042072295322.dkr.ecr.us-east-1.amazonaws.com/awstask:latest
            docker pull 042072295322.dkr.ecr.us-east-1.amazonaws.com/awstask:latest
            docker run -d -p 4043:80 -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --rm 042072295322.dkr.ecr.us-east-1.amazonaws.com/awstask:latest
  
